window.YS_GALLERY = [
  {
    "id": "YS-001",
    "type": "image",
    "extension": "jpg",
    "title": "01",
    "filename": "01.jpg",
    "src": "project-files/assets/chatgpt/01.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-002",
    "type": "image",
    "extension": "jpg",
    "title": "01b",
    "filename": "01b.jpg",
    "src": "project-files/assets/chatgpt/01b.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-003",
    "type": "image",
    "extension": "jpg",
    "title": "01c",
    "filename": "01c.jpg",
    "src": "project-files/assets/chatgpt/01c.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-004",
    "type": "image",
    "extension": "jpg",
    "title": "02",
    "filename": "02.jpg",
    "src": "project-files/assets/chatgpt/02.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-005",
    "type": "image",
    "extension": "jpg",
    "title": "03",
    "filename": "03.jpg",
    "src": "project-files/assets/chatgpt/03.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-006",
    "type": "image",
    "extension": "jpg",
    "title": "04",
    "filename": "04.jpg",
    "src": "project-files/assets/chatgpt/04.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-007",
    "type": "image",
    "extension": "jpg",
    "title": "05",
    "filename": "05.jpg",
    "src": "project-files/assets/chatgpt/05.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-008",
    "type": "image",
    "extension": "jpg",
    "title": "06",
    "filename": "06.jpg",
    "src": "project-files/assets/chatgpt/06.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-009",
    "type": "image",
    "extension": "jpg",
    "title": "07",
    "filename": "07.jpg",
    "src": "project-files/assets/chatgpt/07.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-010",
    "type": "image",
    "extension": "jpg",
    "title": "08",
    "filename": "08.jpg",
    "src": "project-files/assets/chatgpt/08.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-011",
    "type": "image",
    "extension": "jpg",
    "title": "08b",
    "filename": "08b.jpg",
    "src": "project-files/assets/chatgpt/08b.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-012",
    "type": "image",
    "extension": "jpg",
    "title": "08c",
    "filename": "08c.jpg",
    "src": "project-files/assets/chatgpt/08c.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-013",
    "type": "image",
    "extension": "jpg",
    "title": "09",
    "filename": "09.jpg",
    "src": "project-files/assets/chatgpt/09.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-014",
    "type": "image",
    "extension": "jpg",
    "title": "10",
    "filename": "10.jpg",
    "src": "project-files/assets/chatgpt/10.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-017",
    "type": "image",
    "extension": "jpg",
    "title": "ChatGPT Image May 31, 2026 At 11 35 13 AM",
    "filename": "ChatGPT Image May 31, 2026 at 11_35_13 AM.jpg",
    "src": "project-files/assets/chatgpt/ChatGPT%20Image%20May%2031%2C%202026%20at%2011_35_13%20AM.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-018",
    "type": "image",
    "extension": "jpg",
    "title": "King O Diamonds",
    "filename": "King o Diamonds.jpg",
    "src": "project-files/assets/chatgpt/King%20o%20Diamonds.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-019",
    "type": "image",
    "extension": "jpg",
    "title": "Pure Energy Band Logo 02",
    "filename": "Pure Energy band logo 02.jpg",
    "src": "project-files/assets/chatgpt/Pure%20Energy%20band%20logo%2002.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-020",
    "type": "image",
    "extension": "jpg",
    "title": "Pure Energy Band Logo",
    "filename": "Pure Energy band logo.jpg",
    "src": "project-files/assets/chatgpt/Pure%20Energy%20band%20logo.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-022",
    "type": "image",
    "extension": "jpg",
    "title": "Pure Energy Block",
    "filename": "pure energy block.jpg",
    "src": "project-files/assets/chatgpt/pure%20energy%20block.jpg",
    "source": "Chatgpt",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Chatgpt folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-027",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Httpss.Mj.RunB6fNEYDpBoY 3D Cartoon Of Spoc 33257491 7e08 4374 85b7 Aedb711279b1 0",
    "filename": "angeloftheeastbay_httpss.mj.runB6fNEYDpBoY_3D_cartoon_of_Spoc_33257491-7e08-4374-85b7-aedb711279b1_0.jpg",
    "src": "project-files/assets/midjourney/angeloftheeastbay_httpss.mj.runB6fNEYDpBoY_3D_cartoon_of_Spoc_33257491-7e08-4374-85b7-aedb711279b1_0.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-028",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Httpss.Mj.RunStsOS7o CX4 The Man Is Playing 3a1fa064 Bda0 4376 B857 824cc913f6bb 3",
    "filename": "angeloftheeastbay_httpss.mj.runStsOS7o-cX4_The_man_is_playing_3a1fa064-bda0-4376-b857-824cc913f6bb_3.jpg",
    "src": "project-files/assets/midjourney/angeloftheeastbay_httpss.mj.runStsOS7o-cX4_The_man_is_playing_3a1fa064-bda0-4376-b857-824cc913f6bb_3.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-029",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0000 10",
    "filename": "comic-spock-_0000_10.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0000_10.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-030",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0000 12",
    "filename": "comic-spock-_0000_12.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0000_12.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-031",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0000 13",
    "filename": "comic-spock-_0000_13.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0000_13.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-032",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0000 8",
    "filename": "comic-spock-_0000_8.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0000_8.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-033",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0000 9",
    "filename": "comic-spock-_0000_9.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0000_9.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-034",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0001 7",
    "filename": "comic-spock-_0001_7.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0001_7.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-035",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0002 6",
    "filename": "comic-spock-_0002_6.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0002_6.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-036",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0003 5",
    "filename": "comic-spock-_0003_5.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0003_5.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-037",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0004 4",
    "filename": "comic-spock-_0004_4.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0004_4.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-038",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0005 3",
    "filename": "comic-spock-_0005_3.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0005_3.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-039",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0006 2",
    "filename": "comic-spock-_0006_2.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0006_2.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-040",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0007 1",
    "filename": "comic-spock-_0007_1.jpg",
    "src": "project-files/assets/midjourney/comic-spock-_0007_1.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-041",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0000 8",
    "filename": "comic-spock_0000_8.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0000_8.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-042",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0001 7",
    "filename": "comic-spock_0001_7.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0001_7.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-043",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0002 6",
    "filename": "comic-spock_0002_6.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0002_6.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-044",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0003 5",
    "filename": "comic-spock_0003_5.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0003_5.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-045",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0004 4",
    "filename": "comic-spock_0004_4.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0004_4.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-046",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0005 3",
    "filename": "comic-spock_0005_3.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0005_3.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-047",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0006 2",
    "filename": "comic-spock_0006_2.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0006_2.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-048",
    "type": "image",
    "extension": "jpg",
    "title": "Comic Spock 0007 1",
    "filename": "comic-spock_0007_1.jpg",
    "src": "project-files/assets/midjourney/comic-spock_0007_1.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-049",
    "type": "image",
    "extension": "jpg",
    "title": "K Ruanet Star Trek The Next Generation USS Enterprise D Bridge 8d389fd1 Abe9 46b9 Ba49 49896c1cb4da",
    "filename": "k_ruanet_Star_Trek_The_Next_Generation_USS_Enterprise-D_bridge__8d389fd1-abe9-46b9-ba49-49896c1cb4da.jpg",
    "src": "project-files/assets/midjourney/k_ruanet_Star_Trek_The_Next_Generation_USS_Enterprise-D_bridge__8d389fd1-abe9-46b9-ba49-49896c1cb4da.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-052",
    "type": "image",
    "extension": "jpg",
    "title": "UsB0gEIeotvcm4zkIJ9R 1 Deu0w",
    "filename": "usB0gEIeotvcm4zkIJ9R--1--deu0w.jpg",
    "src": "project-files/assets/midjourney/usB0gEIeotvcm4zkIJ9R--1--deu0w.jpg",
    "source": "Midjourney",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2026-08-09",
    "note": "Image from the Midjourney folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-056",
    "type": "image",
    "extension": "jpg",
    "title": "Zarabeth Goodbye 01",
    "filename": "Zarabeth-goodbye-01.jpg",
    "src": "project-files/assets/yesterdays-son-archive/Zarabeth-goodbye-01.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-09-20",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-057",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Pilots Seat Of His Space 05ee857b 4484 49aa 9c1b 1c9b8c1c3738 0",
    "filename": "angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_0.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20pilot%20spock%20PING/angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_0.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-058",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Pilots Seat Of His Space 05ee857b 4484 49aa 9c1b 1c9b8c1c3738 1",
    "filename": "angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_1.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20pilot%20spock%20PING/angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_1.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-059",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Pilots Seat Of His Space 05ee857b 4484 49aa 9c1b 1c9b8c1c3738 2",
    "filename": "angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_2.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20pilot%20spock%20PING/angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_2.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-060",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Pilots Seat Of His Space 05ee857b 4484 49aa 9c1b 1c9b8c1c3738 3",
    "filename": "angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_3.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20pilot%20spock%20PING/angeloftheeastbay_Spock_alone_in_the_pilots_seat_of_his_space_05ee857b-4484-49aa-9c1b-1c9b8c1c3738_3.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-061",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Our Team Needs An Image To Represent The Fo 895e3ecf 7ab4 4a63 9078 C349e7e74758 1",
    "filename": "angeloftheeastbay_Our_team_needs_an_image_to_represent_the_fo_895e3ecf-7ab4-4a63-9078-c349e7e74758_1.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Our_team_needs_an_image_to_represent_the_fo_895e3ecf-7ab4-4a63-9078-c349e7e74758_1.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-03",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-062",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Vast Emptiness Of Space 716277fe 60d7 42cb 906d 60b1577cd071 0",
    "filename": "angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_0.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_0.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-063",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Vast Emptiness Of Space 716277fe 60d7 42cb 906d 60b1577cd071 1",
    "filename": "angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_1.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_1.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-064",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Vast Emptiness Of Space 716277fe 60d7 42cb 906d 60b1577cd071 2",
    "filename": "angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_2.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_2.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-065",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Alone In The Vast Emptiness Of Space 716277fe 60d7 42cb 906d 60b1577cd071 3",
    "filename": "angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_3.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_alone_in_the_vast_emptiness_of_space__716277fe-60d7-42cb-906d-60b1577cd071_3.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-066",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Standing In Deep Shadows On An Alien 4d5c2765 74fb 45aa 858a F20556134019 1",
    "filename": "angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__4d5c2765-74fb-45aa-858a-f20556134019_1.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__4d5c2765-74fb-45aa-858a-f20556134019_1.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-067",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Standing In Deep Shadows On An Alien 4d5c2765 74fb 45aa 858a F20556134019 3",
    "filename": "angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__4d5c2765-74fb-45aa-858a-f20556134019_3.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__4d5c2765-74fb-45aa-858a-f20556134019_3.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-068",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Standing In Deep Shadows On An Alien Dc6558b2 83de 4aaf A1b8 4dd4bd5d327b 2",
    "filename": "angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__dc6558b2-83de-4aaf-a1b8-4dd4bd5d327b_2.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__dc6558b2-83de-4aaf-a1b8-4dd4bd5d327b_2.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-069",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Standing In Deep Shadows On An Alien Dc6558b2 83de 4aaf A1b8 4dd4bd5d327b 3 (1)",
    "filename": "angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__dc6558b2-83de-4aaf-a1b8-4dd4bd5d327b_3 (1).jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__dc6558b2-83de-4aaf-a1b8-4dd4bd5d327b_3%20(1).jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-070",
    "type": "image",
    "extension": "jpg",
    "title": "Angeloftheeastbay Spock Standing In Deep Shadows On An Alien Dc6558b2 83de 4aaf A1b8 4dd4bd5d327b 3",
    "filename": "angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__dc6558b2-83de-4aaf-a1b8-4dd4bd5d327b_3.jpg",
    "src": "project-files/assets/yesterdays-son-archive/night%20spock%20PNG/angeloftheeastbay_Spock_standing_in_deep_shadows_on_an_alien__dc6558b2-83de-4aaf-a1b8-4dd4bd5d327b_3.jpg",
    "source": "Yesterday’s Son Archive",
    "size": "Web optimized",
    "detail": "Web preview; production original retained locally",
    "modified": "2025-08-02",
    "note": "Image from the Yesterday’s Son Archive folder. Prompt and approval notes can be added as the production record develops."
  },
  {
    "id": "YS-076",
    "type": "video",
    "extension": "youtube",
    "title": "The Loneliest Man — Early Animatic",
    "filename": "YouTube 4mZFqxCGZi8",
    "src": "https://www.youtube.com/watch?v=4mZFqxCGZi8",
    "embed": "https://www.youtube-nocookie.com/embed/4mZFqxCGZi8",
    "source": "YouTube",
    "size": "External link",
    "detail": "Earlier animatic / visual-development reference",
    "modified": "2025",
    "external": true,
    "note": "Earlier visual cut preserved as an animatic reference for the upcoming Yesterday's Son music video."
  }
];
